In [1]:
import os
data_path=r"oxbuild_images"

def get_image_paths(data_dir):
    image_paths=[] #图片地址

    for image_dir in os.listdir(data_dir):
        image_path=os.path.join(data_dir, image_dir) 
        image_paths.append(image_path)
 
    return image_paths

# 加载训练集和测试集
image_paths= get_image_paths(data_path)

print("样本数量：", len(image_paths))
print(image_paths)

样本数量： 5063
['oxbuild_images\\all_souls_000000.jpg', 'oxbuild_images\\all_souls_000001.jpg', 'oxbuild_images\\all_souls_000002.jpg', 'oxbuild_images\\all_souls_000003.jpg', 'oxbuild_images\\all_souls_000005.jpg', 'oxbuild_images\\all_souls_000006.jpg', 'oxbuild_images\\all_souls_000007.jpg', 'oxbuild_images\\all_souls_000008.jpg', 'oxbuild_images\\all_souls_000010.jpg', 'oxbuild_images\\all_souls_000011.jpg', 'oxbuild_images\\all_souls_000012.jpg', 'oxbuild_images\\all_souls_000013.jpg', 'oxbuild_images\\all_souls_000014.jpg', 'oxbuild_images\\all_souls_000015.jpg', 'oxbuild_images\\all_souls_000016.jpg', 'oxbuild_images\\all_souls_000017.jpg', 'oxbuild_images\\all_souls_000018.jpg', 'oxbuild_images\\all_souls_000019.jpg', 'oxbuild_images\\all_souls_000020.jpg', 'oxbuild_images\\all_souls_000021.jpg', 'oxbuild_images\\all_souls_000022.jpg', 'oxbuild_images\\all_souls_000026.jpg', 'oxbuild_images\\all_souls_000027.jpg', 'oxbuild_images\\all_souls_000028.jpg', 'oxbuild_images\\all_souls_0

In [3]:
import cv2
import numpy as np
import pickle

sift = cv2.SIFT_create()

# 提取图像特征
def extract_sift_features(image_path):
    image = cv2.imread(image_path)
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    keypoints, descriptors = sift.detectAndCompute(gray_image, None)
    if descriptors is not None:
        return descriptors
    return None

# 提取第一张图像的特征
first_image_features = extract_sift_features(image_paths[0])

# 打印特征
print(first_image_features)

# 存储数据
with open('first_image_features.pkl', 'wb') as f:
    pickle.dump(first_image_features, f)


[[ 6.  0.  0. ...  1.  0.  1.]
 [ 3.  3.  1. ...  5.  3.  2.]
 [28. 48.  7. ... 79.  0.  0.]
 ...
 [34. 17.  0. ... 60.  3.  3.]
 [ 4.  2.  1. ... 14. 14.  1.]
 [ 3.  0.  0. ...  6.  3.  8.]]


In [6]:
import cv2
import numpy as np
sift = cv2.SIFT_create()
# 提取图像特征
def extract_sift_features(image_paths):
    features = []
    for path in image_paths:
        image = cv2.imread(path)
        gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        keypoints, descriptors = sift.detectAndCompute(gray_image, None)
        if descriptors is not None:
            features.append(descriptors)
    return features

import pickle

# 提取图像特征
features = extract_sift_features(image_paths)

# 存储数据
with open('image_features_list.pkl', 'wb') as f:
    pickle.dump(features, f)




In [7]:
# 读取存储的数据
with open('image_features_list.pkl', 'rb') as f:
    loaded_features = pickle.load(f)

# 打印每个元素的大小
for i, feature in enumerate(loaded_features):
    print(f"Loaded feature {i+1} shape: {feature.shape}")

Loaded feature 1 shape: (5257, 128)
Loaded feature 2 shape: (6776, 128)
Loaded feature 3 shape: (2209, 128)
Loaded feature 4 shape: (3462, 128)
Loaded feature 5 shape: (558, 128)
Loaded feature 6 shape: (2682, 128)
Loaded feature 7 shape: (2342, 128)
Loaded feature 8 shape: (3153, 128)
Loaded feature 9 shape: (2251, 128)
Loaded feature 10 shape: (1491, 128)
Loaded feature 11 shape: (6180, 128)
Loaded feature 12 shape: (2597, 128)
Loaded feature 13 shape: (5738, 128)
Loaded feature 14 shape: (2241, 128)
Loaded feature 15 shape: (3254, 128)
Loaded feature 16 shape: (1895, 128)
Loaded feature 17 shape: (2984, 128)
Loaded feature 18 shape: (1035, 128)
Loaded feature 19 shape: (2630, 128)
Loaded feature 20 shape: (3444, 128)
Loaded feature 21 shape: (3644, 128)
Loaded feature 22 shape: (3405, 128)
Loaded feature 23 shape: (3092, 128)
Loaded feature 24 shape: (4816, 128)
Loaded feature 25 shape: (3108, 128)
Loaded feature 26 shape: (3183, 128)
Loaded feature 27 shape: (2039, 128)
Loaded feat

In [ ]:
import cv2
import numpy as np

sift = cv2.SIFT_create()

# 提取图像特征
def extract_sift_features(image_paths):
    all_features = []  # 这将是一个三维列表
    for path in image_paths:
        image = cv2.imread(path)
        gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        keypoints, descriptors = sift.detectAndCompute(gray_image, None)
        if descriptors is not None:
            all_features.append(descriptors.tolist())  # 将numpy数组转换为列表
        else:
            all_features.append([])  # 如果没有描述符，添加一个空列表
    return all_features


# 提取图像特征
features_per_image = extract_sift_features(image_paths)

# 将特征保存为.npy文件
np.save('image_features_list.npy', np.array(features_per_image, dtype=object))


In [2]:
import cv2
import numpy as np
from sklearn.cluster import MiniBatchKMeans

# 初始化SIFT检测器
sift = cv2.SIFT_create()

# 提取图像特征
def extract_sift_features(image_paths):
    features = []
    for path in image_paths:
        image = cv2.imread(path)
        gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        keypoints, descriptors = sift.detectAndCompute(gray_image, None)
        if descriptors is not None:
            features.extend(descriptors)
    return features

# 聚类特征
def clustering(features, num_clusters):
    features = np.array(features)
    kmeans = MiniBatchKMeans(n_clusters=num_clusters, random_state=0, batch_size=100, max_iter=10)
    kmeans.fit(features)
    visual_words = kmeans.cluster_centers_
    return visual_words

# 提取图像特征
features = extract_sift_features(image_paths)

# 假设我们想要的视觉词汇大小为 500
num_visual_words = 500

# 聚类特征以创建视觉词汇
visual_words = clustering(features, num_visual_words)

print("视觉词汇构建完成，词汇大小为:", len(visual_words))


视觉词汇构建完成，词汇大小为: 500


In [6]:
# 保存每张图片的SIFT特征和视觉词汇
np.save('visual_words.npy', visual_words)
np.save('image_features_list.npy', features)

In [2]:
import numpy as np

# 从保存的 NPY 文件中加载特征列表
features = np.load('image_features_list.npy')
print(type(features))
print(len(features))
print(type(features))  # 检查features的类型
print(np.array(features).shape)  # 检查转换为NumPy数组后的形状


<class 'numpy.ndarray'>
17828280
<class 'numpy.ndarray'>
(17828280, 128)


In [5]:
import numpy as np

# 从保存的 NPY 文件中加载特征列表
loaded_features = np.load('image_features_list.npy')

# 获取特征数量和描述符的大小
total_features = len(loaded_features)
descriptor_size = loaded_features.shape[1] if loaded_features.shape[0] > 0 else 0

print("总共加载了 {} 个特征，每个描述符的大小为 {}.".format(total_features, descriptor_size))

总共加载了 17828280 个特征，每个描述符的大小为 128.


In [1]:
import faiss
import numpy as np

def l1_distance(x, y):
    return np.abs(x - y).sum()

def hkm_clustering_faiss(features, num_clusters):
    feature_length = len(features[0])
    index = faiss.IndexIVFFlat(faiss.IndexFlatL2(feature_length), feature_length, faiss.METRIC_L1)  # 使用L1距离

    # 将特征向量添加到索引中
    index.train(np.array(features).astype('float32'))
    index.add(np.array(features).astype('float32'))

    # 初始化聚类中心为随机选择的特征向量
    cluster_centers = np.array(features[np.random.choice(len(features), num_clusters, replace=False)])

    while len(cluster_centers) > num_clusters:
        print(f"Current number of clusters: {len(cluster_centers)}")
        num_clusters = len(cluster_centers)
        new_cluster_centers = []
        new_cluster_assignments = []

        # 分配步骤
        D, I = index.search(np.array(cluster_centers).astype('float32'), 1)  # 找到每个聚类中心最近的特征向量
        for j, idx in enumerate(I.flatten()):
            cluster = features[np.where(I.flatten() == idx)]
            new_cluster_centers.append(np.mean(cluster, axis=0))
            new_cluster_assignments.extend([j] * len(cluster))

        # 更新步骤
        cluster_centers = np.array(new_cluster_centers)
        index.reset()
        index.train(np.array(cluster_centers).astype('float32'))
        index.add(np.array(cluster_centers).astype('float32'))

    return cluster_centers

# 加载特征
features = np.load('image_features_list.npy').astype('float32')

# 视觉词汇大小
num_visual_words = 1000

# 使用HKM进行聚类
visual_words_hkm = hkm_clustering_faiss(features, num_visual_words)
print("HKM视觉词汇构建完成，词汇大小为:", len(visual_words_hkm))

HKM视觉词汇构建完成，词汇大小为: 500


In [3]:
np.save('visual_words_hkm.npy',visual_words_hkm)